# Generated by Django 2.1.7 on 2019-07-14 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190714_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='core.Person'),
        ),
    ]
